spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/PICTURE?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: picture
    password: durtnlchrhtn@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  quartz:
    auto-startup: false
picture:
  upload-path: /Users/sunwoongchoi/Desktop/images/picture # 개인 경로 설정
  pw-salt: durtnlchrhtn@1
  jwt-sign-key: durtnlchrhtn@1
  client-id: applory
  client-secret: durtnlchrhtn@1
logging:
  level:
    com.applory: debug
    org.springframework.messaging: debug

